### ISSUE TITLE
很感兴趣。想参考。是要自己签名么？

### ISSUE THREAD

**Issue by Lemniscate317** [JustWayward/BookReader#1]
`Could not find property 'KEYSTORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.`
是用自己的签名么。
感谢分享

**Comment by smuyyh** [comment]
签名自己替换

**Comment by smuyyh** [comment]
签名文件提供了。更新试试~

**Comment by Lemniscate317** [comment]
自己弄了一个。可以了。就是我要看一下那三个框架怎么用才能更好看懂代码。我主要是参考读书的那个界面的。包括pagefactory，和弹出的菜单是怎么回事之类的。很感谢开源，因为这方面找不到太好的资源

**Comment by smuyyh** [comment]
那就是分页算法了，确实资料很少，我也就自己瞎写了一个，勉强可以用，不过还是有很多不足的地方，正准备后面再想想~这方面有想法也可以交流下哈~~
