### ISSUE TITLE
 能否提供其他阅读字体下载？

### ISSUE THREAD

**Issue by howie6879** [JustWayward/BookReader#100]
非常好的app，感谢作者的付出：
我有点小问题
我用的时候点击登录没反应
小说的源是固定的吗
阅读字体能否更改
导入epub书籍显示乱码
非常感谢。

**Comment by smuyyh** [comment]
1. 登录这块可能实现不了，不准备做了，还未移除。收藏之类的只停留于本地缓存级别。
2. 目前小说源是固定的，换源正考虑加入。
3. 阅读字体需要换的话，可以在自行再绘制的时候加入，因为字体包比较大，目前没有加入。
4. epub功能还不太稳定，乱码是指页面乱码？

**Comment by howie6879** [comment]
导入epub，显示却是txt 然后打开全部乱码

在 2017年2月16日 上午9:15，LeBron_Six <notifications@github.com>写道：

**Comment by yanghuaangel** [comment]
内存的使用率太高了，比较致命，能知道哪里占用了大量的内存吗，我看都要到70--80M左右

**Comment by smuyyh** [comment]
@yanghuaangel 还没去排查。后面再加个内存泄漏检测
