### ISSUE TITLE
请问下怎么统计一章有多少页

### ISSUE THREAD

**Issue by rtyheji** [JustWayward/BookReader#102]

**Comment by smuyyh** [comment]
目前因为章节页数基本不多，所以实际上是章节分页一遍，才知道多少页。其他方式，也只能大概计算多少页吧。

**Comment by rtyheji** [comment]
请问下你里面的有变量有直接得到一章总页数的值的吗

**Comment by smuyyh** [comment]
没有。

**Comment by rtyheji** [comment]
章节分页一遍是在哪个函数里

**Comment by smuyyh** [comment]
哦看了一下我之前好像把计算页数的去掉了，目前是显示百分比。计算页数的话可以参考```com.justwayward.reader.view.readview.PageFactory#pageDown```方法。这个是读一页，可以循环读到结束。
