### ISSUE TITLE
DaggerCommunityComponent找不到

### ISSUE THREAD

**Issue by xingjiyihao** [JustWayward/BookReader#105]
在工程里面，com.justwayward.reader.component.DaggerCommunityComponent中没有DaggerCommunityComponent这个类啊，一直报错，找不到这个类，求大神指点

**Comment by smuyyh** [comment]
#53

**Comment by xingjiyihao** [comment]
这个DaggerCommunityComponent类是在编译中自动生成的吗

**Comment by xingjiyihao** [comment]
你好，编译也通不过啊，直接报找不到DaggerCommunityComponent这个类

**Comment by smuyyh** [comment]
没编译对吧。ReBuild一下。这个的Dagger2自动生成的~

**Comment by xingjiyihao** [comment]
能加你qq吗
