### ISSUE TITLE
翻到某一页会一直出现“哎呀程序崩溃拉'

### ISSUE THREAD

**Issue by rtyheji** [JustWayward/BookReader#108]
va.lang.IndexOutOfBoundsException: index=-4, limit=8731
02-27 11:01:43.541 4046-4046/com.justwayward.reader E/BookReader:     at java.nio.Buffer.checkIndex(Buffer.java:156)
02-27 11:01:43.541 4046-4046/com.justwayward.reader E/BookReader:     at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:157)
02-27 11:01:43.541 4046-4046/com.justwayward.reader E/BookReader:     at com.justwayward.reader.view.readview.PageFactory.readParagraphForward(PageFactory.java:472)
02-27 11:01:43.541 4046-4046/com.justwayward.reader E/BookReader:     at com.justwayward.reader.view.readview.PageFactory.pageDown(PageFactory.java:319)
02-27 11:01:43.541 4046-4046/com.justwayward.reader E/BookReader:     at com.justwayward.reader.view.readview.PageFactory.nextPage(PageFactory.java:541)
02-27 11:01:43.541 4046-4046/com.justwayward.reader E/BookReader:     at com.justwayward.reader.view.readview.BaseReadView.onTouchEvent(BaseReadView.java:134)

这是错误日志

**Comment by smuyyh** [comment]
不好意思  前段时间比较忙   这个问题是经常出现的还是？你这应该是比较早的代码了吧  现在都对不上这个代码的行数了。

**Comment by rtyheji** [comment]
我是下载你的代码然后编译下的  就是某一页会这样 然后就过不去了，点目录换一章就好了

**Comment by smuyyh** [comment]
清除一下对应那本书籍的缓存应该就可以了。 可能是缓存阅读位置之后，章节内容变了。
