### ISSUE TITLE
CollectionsManager 出现空指针异样

### ISSUE THREAD

**Issue by yxhuangCH** [JustWayward/BookReader#11]
CollectionsManager line 79  出现空指针异常

public boolean isCollected(String bookId) {
        List<Recommend.RecommendBooks> list = getCollectionList();
        for (Recommend.RecommendBooks bean : list) {   // 报空指针异样
            if (bean._id.equals(bookId)) {
                return true;
            }
        }
        return false;
    }

getConllectionList() 方法会返回 null 的。所以在 for 循环之前先加判断。
这是修改之后的
 public boolean isCollected(String bookId) {
        List<Recommend.RecommendBooks> list = getCollectionList();
        if (list == null ) return  false;
        
        for (Recommend.RecommendBooks bean : list) {   
            if (bean._id.equals(bookId)) {
                return true;
            }
        }
        return false;
    }

**Comment by smuyyh** [comment]
好的~~  THX
