### ISSUE TITLE
关于左右滑动的bug

### ISSUE THREAD

**Issue by cocoas** [JustWayward/BookReader#111]
在使用的时候，如果我在屏幕的右边像左滑会滑到右边去，在右边向左滑会滑到右边去，或者是直接滑不动

**Comment by smuyyh** [comment]
目前是判断手指触摸区域。ACTION_DOWN 在右边的1/3 就只能往下翻页。在左边的1/3 就只能往前翻页。中间区域为菜单响应区

2017-03-03 11:25 GMT+08:00 cocoas <notifications@github.com>:

**Comment by cocoas** [comment]
因为阅读时候是想不管在哪个区域左滑右滑都可以，所以觉得是bug，不知道大神能否处理下

**Comment by smuyyh** [comment]
恩，这个体验确实不怎么好。后期有时间还会继续优化的~

**Comment by sanshierli** [comment]
大神,安装好体验demo显示没有网络呢

**Comment by smuyyh** [comment]
不会吧...  啥情况

**Comment by sanshierli** [comment]
今天刚出现的好像,昨天还没事呢...又试了下,4G没事,WiFi不行,见鬼

**Comment by smuyyh** [comment]
那就是你wifi网络的问题了吧~~

**Comment by sanshierli** [comment]
嗯,应该是我自己的问题,..顺便感谢一下大神分享出这么优秀的代码来参考学习!
