### ISSUE TITLE
大神经常翻页翻到某一章的最后一页 再往下一章翻的时候提示程序奔溃了，点目录直接选下一章进去是正常的。。。。我这边试了大主宰和圣墟有这问题。。。

### ISSUE THREAD

**Issue by rtyheji** [JustWayward/BookReader#115]

**Comment by smuyyh** [comment]
log 有么？贴一下

**Comment by rtyheji** [comment]
java.lang.IndexOutOfBoundsException: index=-88, limit=8991
at java.nio.Buffer.checkIndex(Buffer.java:156)
03-17 09:44:02.324 4351-4351/com.justwayward.reader E/BookReader:     at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:157)
03-17 09:44:02.324 4351-4351/com.justwayward.reader E/BookReader:     at com.justwayward.reader.view.readview.PageFactory.readParagraphForward(PageFactory.java:472)
03-17 09:44:02.324 4351-4351/com.justwayward.reader E/BookReader:     at com.justwayward.reader.view.readview.PageFactory.pageDown(PageFactory.java:319)
03-17 09:44:02.324 4351-4351/com.justwayward.reader E/BookReader:     at com.justwayward.reader.view.readview.PageFactory.nextPage(PageFactory.java:541)
03-17 09:44:02.324 4351-4351/com.justwayward.reader E/BookReader:     at com.justwayward.reader.view.readview.BaseReadView.onTouchEvent(BaseReadView.java:134)
03-17 09:44:02.324 4351-4351/com.justwayward.reader E/BookReader:     at android.view.View.dispatchTouchEvent(View.java:7734)
03-17 09:44:02.324 4351-4351/com.justwayward.reader E/BookReader:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
03-17 09:44:02.324 4351-4351/com.justwayward.reader E/BookReader:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
03-17 09:44:02.324 4351-4351/com.justwayward.reader E/BookReader:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)

**Comment by smuyyh** [comment]
加一下QQ哈~~   352091626 确认一下问题
