### ISSUE TITLE
大神，你知道怎么实现类似掌阅的那种想法标签效果吗？

### ISSUE THREAD

**Issue by q232916067** [JustWayward/BookReader#119]
就是每一段文字的结尾，如果有读者想法，就会有一个灰色的小圆圈，点击可以弹出一个window

**Comment by smuyyh** [comment]
不太确定。说说我的看法吧
1. 可能可以选择继承RelativeLayout等ViewGroup，最后一页往里面添加控件。
2. 直接绘制，判断点击事件是否在该rect内，响应。
