### ISSUE TITLE
第三方登录无效，QQ授权完无反应。

### ISSUE THREAD

**Issue by lsh93** [JustWayward/BookReader#122]
微博微信点击没有调用相关APP。我有一个自动阅读的梦，大大要不要加一下。😂😂😂

**Comment by smuyyh** [comment]
@lsh93 登录这块后期准备去掉，第三方貌似无法登录到追书后台。 收藏在本地

**Comment by lsh93** [comment]
@smuyyh  登录去掉更好，代码上好改，主要是自动阅读能不能考虑加一下。

**Comment by smuyyh** [comment]
自动阅读？
自动滚动？

**Comment by lsh93** [comment]
@smuyyh  是的，自动滚动小说，支持调整滚动速度，无限卷帘，不用手翻，这样就完美咯。方便透露一下下个版本大概在什么时候出嘛。
