### ISSUE TITLE
Convert to English

### ISSUE THREAD

**Issue by mjobanputra** [JustWayward/BookReader#123]
How to convert this to english. i tried to load an english pdf file but it  opened in Chinese language and it was not in readable format can you please help me. i want to open pdf  in english language

**Comment by smuyyh** [comment]
Do you mean app language?

**Comment by mjobanputra** [comment]
yeah and also my english pdf is not opening in english language is converted or something

**Comment by mjobanputra** [comment]
Its in english but but its converted to Chinese. can you help me with it??

![device-2017-04-05-194303](https://cloud.githubusercontent.com/assets/22979625/24709634/2b1f31bc-1a38-11e7-8803-1544d0d46f96.png)

**Comment by smuyyh** [comment]
@mjobanputra This reading ui only supports TXT format files, PDF format file is opened through the built-in PDF reader in this app. What I want to know is that your PDF file suffix is capitalized. In my code, it is not case sensitive. It may cause it to find the corresponding reader.

Or, can you send me this PDF file.

**Comment by mjobanputra** [comment]
this is the pdf i'm trying to open
[BlackBookOfComputerVirus.pdf](https://github.com/JustWayward/BookReader/files/901563/BlackBookOfComputerVirus.pdf)

**Comment by smuyyh** [comment]
In my device, it can open normally.

<img src="https://cloud.githubusercontent.com/assets/15133565/24739611/6e72b6d6-1acf-11e7-980f-887fbf1ee353.png" width="250" /> <img src="https://cloud.githubusercontent.com/assets/15133565/24739646/97ba4874-1acf-11e7-98a1-8ca7a98c0224.png" width="250" />

and it can also be opened directly through the file manager.

<img src="https://cloud.githubusercontent.com/assets/15133565/24739738/0a4ae9e8-1ad0-11e7-919b-1bf8b56fc7ee.png" width="250" />

**Comment by smuyyh** [comment]
Are you compiled “BookReader” project by the latest code?

**Comment by mjobanputra** [comment]
i downloaded it before 3 days

**Comment by mjobanputra** [comment]
i transferred it via wifi option in the app may be thats why it became txt from pdf file?
it shows as txt in file list

**Comment by smuyyh** [comment]
Aha. Wifi transmission only support TXT file，by default, the stream is saved as a TXT file, other types of files are not supported by it.

**Comment by mjobanputra** [comment]
ohk so that was the problem....thanx for the solution :)

**Comment by smuyyh** [comment]
don't mention it~
