### ISSUE TITLE
导入android studio项目显示异常

### ISSUE THREAD

**Issue by muxiaofufeng** [JustWayward/BookReader#124]
您好，导入android studio的时候不能正常显示 modules 里面的主项目跟libraries之间的关系，导致不能项目不能运行，请教一下该怎么解决

**Comment by smuyyh** [comment]
是不是AS版本太低，或者对应Gradle版本、buildTools版本等 没有~  可以多试试

**Comment by Alvin9234** [comment]
代码上传不完整吧，缺少好多文件，component包下，还有moudle下，等等。
