### ISSUE TITLE
无法拉去图书列表

### ISSUE THREAD

**Issue by 1198681139** [JustWayward/BookReader#127]
我在用这个开源项目做我们SDK的测试，今天发现，只有我的测试手机安装后无法拉去阅读列表等信息，一直提示没有网络，可是我的其他APP网络访问一直正常。请教，是不是你们的服务器test.api.hcicloud.com把的手机给封了，还是访问网络你们有次数或是什么的限制。

**Comment by smuyyh** [comment]
test.api.hcicloud.com？没用到这个吧

**Comment by 1198681139** [comment]
没有使用，后来发现是读取imei所需要权限的问题。
