### ISSUE TITLE
怎么会用mvp去写？

### ISSUE THREAD

**Issue by liupeng110** [JustWayward/BookReader#128]

**Comment by liupeng110** [comment]
本来想给你点个赞的，但是看了你的代码 除了项目目录清晰  其他的真是，感觉写的太傻了

**Comment by smuyyh** [comment]
菜鸟一枚，多多指点~~

**Comment by liupeng110** [comment]
你写完了别人能看的懂么？要花多长时间看懂？

**Comment by liupeng110** [comment]
代码逻辑 要花多长时间捋顺？

**Comment by smuyyh** [comment]
所以你觉得得怎么写  才能让别人看懂？

**Comment by liupeng110** [comment]
1. butterknife每次都oncreate   里初始化累不累
2.滥用回调和接口   -----严重打乱了代码本身逻辑          
3.过度封装  引入过多无用的类           简为美

**Comment by smuyyh** [comment]
好吧 受教了~~

**Comment by liupeng110** [comment]
另外书架上的书突然全没了，清空缓存不要清空书架啊  
我又换回了 书旗破解版  借鉴下别人家的仿真页面的处理  
翻页不到一半是没有翻过去的

**Comment by rtyheji** [comment]
请问下书旗破解版源码有吗
