### ISSUE TITLE
pdf无法查看

### ISSUE THREAD

**Issue by fangjianwei555** [JustWayward/BookReader#131]
大神你好，我想单独集成pdf阅读部分，把pdfview文件夹下的东西都已经集成到我的代码中，代码都没有报错，但是pdf不显示，而且标题名字也可正常显示pdf的名称  请问大神大概是什么原因导致的呢

**Comment by smuyyh** [comment]
这样有点泛了，没法确定~  pdf用的是Android SDK自带的，可以查一下具体使用方式
