### ISSUE TITLE
Enquiry: Server Side Code?

### ISSUE THREAD

**Issue by anburocky3** [JustWayward/BookReader#140]
Hello Author, 
I have downloaded and working on the Book reader. But i cant find the API of Server Side coding ?
May i have the server side coding of this project?
Thank you

**Comment by smuyyh** [comment]
I am very sorry about it, all API are obtained from the app which names "ZhuiShuShenqi"

[http://www.zhuishushenqi.com/download](http://www.zhuishushenqi.com/download)
