### ISSUE TITLE
大神，源码缺少文件啊DaggerMainComponent没有

### ISSUE THREAD

**Issue by breakfrox** [JustWayward/BookReader#141]
import com.justwayward.reader.component.DaggerMainComponent;

**Comment by Devin1102** [comment]
注释掉，然后打开注释就可以了

**Comment by smuyyh** [comment]
#53 
本质上是需要Build以下才生成的！

**Comment by breakfrox** [comment]
不是，我看了导包，这是自己写的，不是build生成的，但是没有这个文件

**Comment by smuyyh** [comment]
。。。。 就是Dagger2自动生成的那个类！ 不懂的话可以先去了解一下

**Comment by breakfrox** [comment]
0 0 这样啊
