### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ozy20** [JustWayward/BookReader#144]
列表数据重复，应该是显示了缓存数据，网络一遍又重复加载了

**Comment by smuyyh** [comment]
目前的策略确实是先加载缓存。哪个页面出现的呢

**Comment by ozy20** [comment]
基本每个都有吧，有网络的情况下，这里这个缓存机制是加载缓存后还会继续加载网络的数据

**Comment by ozy20** [comment]
我看的是书荒区那个列表，重复确实存在，其他界面缓存的应该也是一样的
