### ISSUE TITLE
仿真翻页效果

### ISSUE THREAD

**Issue by libin1993** [JustWayward/BookReader#147]
大神，我正在做仿真翻页加载网络图片效果，左滑下一页，右滑上一页，点击页面跳转功能。网上只有hmg的pagewidget和android_page_curl这两个控件，pagewidget滑动翻页有问题，page_curl在部分三星手机上点击不能跳转。请问解决全屏点击事件和滑动的冲突呢，还有右滑上一页翻页怎么实现合书的效果呢？

**Comment by smuyyh** [comment]
这个当时也是用hmg的那个改的。
