### ISSUE TITLE
根据百分比跳转

### ISSUE THREAD

**Issue by pengchenwei** [JustWayward/BookReader#149]
你好，我在项目中有一个百分比跳转函数，但是很可惜，好像并没有用到
![image](https://cloud.githubusercontent.com/assets/17327531/26715277/ad26581a-47a7-11e7-928f-e773aa556401.png)
我觉得这是一个很常用的功能，为什么会被隐掉，如果我要实现这个功能您有什么建议？
参考：com/justwayward/reader/view/readview/PageFactory.java:582

另外，在查看本地书籍时，底部的进度百分比一直是100%，这个的计算是不是可以优化一下，分为本地书籍和在线书籍呢？

**Comment by smuyyh** [comment]
这个本来是要做进度条拖动的  感觉不是很好  就去掉了

**Comment by pengchenwei** [comment]
“感觉不是很好”是指的实现不好做还是功能体验不好？

**Comment by pengchenwei** [comment]
我还想问一下，有没有翻页动画完成的回调或者标识？我现在翻页完成后对页面进行重绘处理，谢谢

**Comment by smuyyh** [comment]
在onComputerScroll里面获取。

**Comment by pengchenwei** [comment]
![image](https://user-images.githubusercontent.com/17327531/26893385-b56cee54-4bed-11e7-91b3-57a3efba3a6a.png)
computeScroll里面返回结束状态后还要最后再绘制一次，这个怎么判断是最后一次绘制完成？（这只是点击翻页）

滑动翻页，computeScroll会返回多次结束绘制：
![image](https://user-images.githubusercontent.com/17327531/26893550-3b6bab30-4bee-11e7-99a3-0b12603bfc3f.png)
→_→心好累

**Comment by smuyyh** [comment]
小伙子你这么拼你家里人知道么？
