### ISSUE TITLE
求个包

### ISSUE THREAD

**Issue by 1608637229** [JustWayward/BookReader#15]
有编译好的包吗，

**Comment by smuyyh** [comment]
链接: https://pan.baidu.com/s/1i5PT6dR 密码: c82u

**Comment by 1608637229** [comment]
谢谢

**Comment by 1608637229** [comment]
试了下，基本无法使用，cm13，反馈下问题吧，加载不出来任何东西，似乎没有网络哦，但是我网络是正常的，排行榜点击追更新没反应，点击开始阅读FC，设置里除了登录和夜间模式其他都没用，不知道是不是不兼容CM13或者说是6.0，等修复更新吧，我可以帮忙内测下

**Comment by smuyyh** [comment]
有部分功能还没完成。点击没反应的就是还没做的部分。至于你说的加载不出任何东西来，不会吧？

**Comment by smuyyh** [comment]
应该是6.0的问题。权限我还没处理，马上处理一下~  感谢提醒

**Comment by 1608637229** [comment]
好的，等更新

**Comment by smuyyh** [comment]
链接: https://pan.baidu.com/s/1cyx2VG 密码: 8wbk
再试试

**Comment by 1608637229** [comment]
能用了
