### ISSUE TITLE
偶现OOM

### ISSUE THREAD

**Issue by Learzhu** [JustWayward/BookReader#158]
在Android4.4或者以下的手机上翻页的时候可能出现OOM奔溃Bitmap.createmap()

**Comment by smuyyh** [comment]
早前写的了，这方面都没优化，最近比较忙~

**Comment by Learzhu** [comment]
嗯嗯，试了好几天还是没法搞定OOM的问题额

**Comment by smuyyh** [comment]
http://www.coolapk.com/apk/com.yanshi.writing
