### ISSUE TITLE
翻页滑动

### ISSUE THREAD

**Issue by Learzhu** [JustWayward/BookReader#159]
希望在屏幕左侧向左也可以滑动，右侧向右也可以滑动，发现使用当前的实现方式上很难实现，期待改进

**Comment by smuyyh** [comment]
这个要改就得大改了，主要是现在没什么时间来改这个。

**Comment by Learzhu** [comment]
是的，实现方式就得改变了……

**Comment by smuyyh** [comment]
主要是提供一个思路。  其实从新写滑动翻页这块不难的，主要就是处理触摸和Scroller、还有绘制。
