### ISSUE TITLE
未允许获取手机信息(号码, IMEI, IMSI等)会导致不能搜索小说, 排行榜里的 也不能加书架

### ISSUE THREAD

**Issue by lzpong** [JustWayward/BookReader#168]
未允许获取手机信息(号码, IMEI, IMSI等)会导致不能搜索小说, 排行榜里的 也不能加书架
这是不是Bug ???

**Comment by smuyyh** [comment]
不是。因为追书的api  要求有deviceid的，这个我也没办法。

**Comment by lzpong** [comment]
不可以随机一个数字？  每次安装 或 运行  的时候？

**Comment by lzpong** [comment]
有没有 搞个 群 啊，

**Comment by smuyyh** [comment]
估计也可以。没仔细研究

**Comment by lzpong** [comment]
换源， 是不是 追书api 不支持，我发现 换 id 请求的都是空或者错误， 换link 没看到支持的

**Comment by lzpong** [comment]
IMEI 的获取 我直接 随机数了 嘿嘿
···java
    public static String getIMEI(Context context) {
        if(IMEI.isEmpty()) {
            String r1=""+(Math.random()*1000000000000000L);
            IMEI=r1.substring(0,14);
        }
        //TelephonyManager telephonyManager = (TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE);
        //String IMEI = telephonyManager.getDeviceId();
        LogUtils.i(TAG, "getIMEI: "+IMEI);
        return IMEI;
    }
···

**Comment by smuyyh** [comment]
换源这块  接口好乱，我都没理解清楚。

**Comment by lzpong** [comment]
换源我已经搞好了，包括阅读，嘿嘿，如下接口
目录：
http://api.zhuishushenqi.com/toc/5830780f261361da51ee8175?view=chapters

BookApiService：
    @GET("/atoc/{bookId}")
    Observable<BookToc> getBookAToc(@Path("bookId") String bookId, @Query("view") String view);

现在在搞换源后的数据详情
