### ISSUE TITLE
缓存更新

### ISSUE THREAD

**Issue by zengcanxiang** [JustWayward/BookReader#17]
一本书没有写完的时候，我缓存了全本，并且看完了，后面他更新了，追书界面的章节目录变为最新的，但是进入阅读，却是100%。无法加载下一页，阅读界面的章节目录显示的也不是最新的。
![screenshot_2016-09-30-09-17-48-1239109155](https://cloud.githubusercontent.com/assets/16033497/18977680/f3f56332-86ee-11e6-8fcb-cf5caa75f70f.png)
![screenshot_2016-09-30-09-18-04-1147625795](https://cloud.githubusercontent.com/assets/16033497/18977678/f3f37018-86ee-11e6-9742-1f5f7b19724d.png)
![screenshot_2016-09-30-09-17-56-1005869920](https://cloud.githubusercontent.com/assets/16033497/18977679/f3f50da6-86ee-11e6-9798-57988d7d566d.png)

**Comment by zengcanxiang** [comment]
好几本是这样，是API的问题还是更新缓存的问题.....

**Comment by smuyyh** [comment]
缓存的问题。我缓存了目录 所以...  这个还得研究一下API看怎么判断有更新，就清除目录缓存

**Comment by zengcanxiang** [comment]
难怪，我删除了书籍但是还是看不了，而且没加入书架也不行。这就引出了另一个问题，删除数据同时删除缓存的时候，没有删除你说的目录缓存。

**Comment by smuyyh** [comment]
对。等下就加上~   3Q

**Comment by zengcanxiang** [comment]
还有一个问题，我昨天更新你们的代码之后，一本新书加载书籍告诉我加载失败，其他的都可以，不知道为什么。而且在进入加载界面的时候，最好不要碰屏幕，碰了好像就不会加载了，要退出去在来一次

**Comment by zengcanxiang** [comment]
我觉得，在每本书最好加上一个是否缓存的标志，因为我缓存了一本书，然后看其他书去了，我不知道他缓存完了没有，我经常缓存几次。。。。

**Comment by smuyyh** [comment]
实际上没有缓存好几次。我是判断他章节文件有没有存在，有存在直接跳过~  没有重新请求的

**Comment by zengcanxiang** [comment]
我看到了提示是否存在了缓存队列，但是，你看下这种情况会怎么处理。就是100章，我在阅读界面启动缓存，然后他开始提示1章，2章的，然后我退出，他会在后台缓存么？如果我进去在缓存，他是从头缓存还是接着缓存，还是不缓存？因为我重新进去，好像是没有提示已存在缓存队列的.....

**Comment by zengcanxiang** [comment]
@smuyyh 请问在首页下拉更新书籍内容是可以的么，感觉还是不行呢，目录还是没有更新

**Comment by smuyyh** [comment]
现在目录会在阅读的时候去更新一次。下拉刷新没有更新目录
