### ISSUE TITLE
重大问题***，怎么阅读页面会出现重影叠加的问题？？？？？？

### ISSUE THREAD

**Issue by tjt852** [JustWayward/BookReader#170]
想问一下PageFactory类的onDraw方法，，，没多次调用后再执行，之前是在哪儿清空画布的？？？？？？我的会出现图片叠加状况，，，基础类代码都没改
![image](https://user-images.githubusercontent.com/5794936/28747658-f3cdcd64-74d6-11e7-816e-f8701ebff7c8.png)

**Comment by tjt852** [comment]
我在这里加了一行代码就好了，清空一下，但是不知道为什么你的项目运行就没问题，，，放到我项目里就出现问题，虽然解决了，但还是求解答
![image](https://user-images.githubusercontent.com/5794936/28747713-dd472d28-74d7-11e7-9d06-095bb44e3ffa.png)

**Comment by smuyyh** [comment]
绘制背景，目的就是把之前的覆盖掉。绘制文字前都会先绘制背景

**Comment by smuyyh** [comment]
一看时间，通宵撸代码的节奏？你很拼，领导很看好你，明天给你涨工资。
