### ISSUE TITLE
大神，能增加一个笔记的功能吗

### ISSUE THREAD

**Issue by ainiyiwan** [JustWayward/BookReader#173]

**Comment by smuyyh** [comment]
啥笔记功能，你是说保存文字片段？

**Comment by ainiyiwan** [comment]
是的，可以选择复制文字片段

**Comment by ainiyiwan** [comment]
对了，刚才发现两个不错的开源项目，翻页效果和复制的功能都很赞，推荐给你看看，好多代码看不太懂，希望大神可以研究研究，为我们伟大的开源世界做贡献
https://github.com/ydcx/KooReader
https://github.com/geometer/FBReaderJ
貌似还有C的

**Comment by ainiyiwan** [comment]
另外，詹姆斯那张图片很帅，不过，我是库迷。。。

**Comment by smuyyh** [comment]
自定义view绘制的文字，要选中文字相当麻烦😂😂库里最近中国行没去看看？
