### ISSUE TITLE
阅读本地小说时无法显示阅读进度(阅读时的页面, 总显示100%)

### ISSUE THREAD

**Issue by a442509097** [JustWayward/BookReader#175]
还有一个问题就是, 当阅读一篇本地的一般小说(无目录信息), 也正因为本地小说的关系, 有没有办法加入拖动跳转到指定百分比内容, 如果是读取一个7m左右的txt文件, 用BufferedReader会不会有问题, 还是说只能转换成SQLite实现跳转功能?

**Comment by smuyyh** [comment]
进度的问题是因为之前并没有按分页页数来算，而是按章节。本地导入，认为是一章，所以没变化。这个后续有时间会把整块阅读部分做一个重构。

7m即使BufferReader没问题，以目前的算法直接做分页是不行的，效率不行，这个分页算法也需要改进。

https://www.coolapk.com/apk/com.yanshi.writing  可以看看里面的阅读模块，这是我重新写的。
