### ISSUE TITLE
epub书籍中有生僻字的时候，生僻字单独一行

### ISSUE THREAD

**Issue by xuedongchao** [JustWayward/BookReader#191]
生僻字本来是与上下文字连起来的，但是，那个生僻字（图片）单独作为一个段落了，影响了本来的排版布局。

**Comment by smuyyh** [comment]
嗯，对epub的支持不是很好。

**Comment by xuedongchao** [comment]
能弱弱的问一下，有啥开源的epub3的阅读器吗？想借鉴一下。

**Comment by smuyyh** [comment]
最近都没研究这个了    java下之前也就发现那么一个  兼容性不是很好
