### ISSUE TITLE
Android Studio 3.0 build 出问题

### ISSUE THREAD

**Issue by 164738777** [JustWayward/BookReader#195]
<img width="764" alt="2017-11-21 12 23 28" src="https://user-images.githubusercontent.com/21001567/33028960-3eb07046-ce52-11e7-839e-e09c584e30bb.png">

gradle tool 改成 3.0.0，

gradle 版本改成 4.2.1-all的，

其他设置或者代码均没改动。

但是出现如图错误，求大佬帮忙～

**Comment by smuyyh** [comment]
是不是被墙下载不下载   或者clean一下

**Comment by 164738777** [comment]
把 gradle 里面相关apt设置、release设置注释掉

**Comment by sevenchrishai** [comment]
apt插件问题,参考[这里](http://blog.csdn.net/qq_34020571/article/details/78421091)
