### ISSUE TITLE
Add English translation of readme

### ISSUE THREAD

**Issue by astromme** [JustWayward/BookReader#199]
My 中文 isn't very good. Can you add an English translation to the readme to help?

**Comment by smuyyh** [comment]
@astromme The readme.md is nothing useful here，what kind of information would you like to know？

**Comment by astromme** [comment]
I'm looking for libraries to make it easier to develop an ebook reader on Android. I'm wondering if this project might be helpful.

**Comment by smuyyh** [comment]
Okay, Readme has no information on this, it may be useful to see at the code directly
