### ISSUE TITLE
很不错的项目，不知道能不能参考一下图书 api

### ISSUE THREAD

**Issue by hymanme** [JustWayward/BookReader#2]
不知道有没有 api 文档，我在搜书神器网上没找到。谢谢！

**Comment by lfh1991** [comment]
api文档暂时还没有，BookApiService这个类里有关于api的注释，你可以先看看

**Comment by smuyyh** [comment]
API不是开放的。网上肯定也找不到~ 文档其实可以直接参考BookApiService，基本有注释。

**Comment by hymanme** [comment]
好的，谢了。

**Comment by aitwx** [comment]
想问楼主是怎么搞到追书神器的API的？破译？还是监视APK的网络请求？用的什么技术呢

**Comment by lfh1991** [comment]
@aitwx 用charles抓的

**Comment by griefcola** [comment]
这样用，会不会被追书封？
需要配套的服务端项目吗？我打算开一个

**Comment by smuyyh** [comment]
@griefcola 合适的话也是可以的。有意加Q细聊~352091626
