### ISSUE TITLE
追书的api如何拿到的

### ISSUE THREAD

**Issue by nanweiqing** [JustWayward/BookReader#20]
博主，能不能抽时间就如何获取应用的api写个博客啊，想学习下，很好的项目

**Comment by smuyyh** [comment]
就是抓包的，没啥技术含量😏

**Comment by Sirierx** [comment]
but对小白来说,没技术含量的抓包也很难呀,希望博主能抽空写个教程什么的,谢谢~

**Comment by smuyyh** [comment]
这个好像有点不厚道....  动手试试，不难的。没几个步骤，我用的是Charles，你们可以试试~

**Comment by smuyyh** [comment]
@nanweiqing @Sirierx 晚点写一篇，明天发你们。

**Comment by qw4096** [comment]
@smuyyh 同求，大神

**Comment by smuyyh** [comment]
@nanweiqing @Sirierx @qw4096 http://blog.csdn.net/yyh352091626/article/details/52759294

**Comment by jxxfzgy** [comment]
能抓到qq阅读的数据吗

**Comment by smuyyh** [comment]
@jxxfzgy 这个倒没试过，你可以抓一下看
