### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by HanCheng** [JustWayward/BookReader#200]
Git clone your project and got this error.

com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/chan/Documents/AndroidSDK/sdk/build-tools/23.0.3/aapt'' finished with non-zero exit value 1

any ideas? I am using AS 3.1 Preview

**Comment by smuyyh** [comment]
update gradle tools and try it.
