### ISSUE TITLE
迫切需要翻页效果

### ISSUE THREAD

**Issue by mdlboe** [JustWayward/BookReader#23]
翻页效果 怎么网上都找不到开源的啊  一般的阅读器左右平滑 上下滑动 仿真 仿真像QQ阅读那样的比较好,现在用的最多的我感觉还是上下 和 左右滑动两种,   大神有这方面的资源吗?

**Comment by TonyJason** [comment]
https://github.com/wanpg/51Read
https://github.com/PeachBlossom/treader
https://github.com/xufeifandj/MReader
https://github.com/whyisandroid/EEEReader
这些都是哈

**Comment by smuyyh** [comment]
@mdlboe http://download.csdn.net/detail/yyh352091626/9648085 这个有ViewPager式的滑动翻页和滑动覆盖翻页，跟追书比较像。

**Comment by vainly** [comment]
@smuyyh  https://github.com/martiansutdio/SlidingLayout.git，下载下来看了，确实比较像，能否加入到项目中？

**Comment by smuyyh** [comment]
有准备加入这个效果。等剩余功能完善了再来~
