### ISSUE TITLE
uc的小说书架收费后，就一直在找，终于找到一个。

### ISSUE THREAD

**Issue by anshe80** [JustWayward/BookReader#24]
大神真是厉害，已下载试用，虽然还有很多功能没有实现，不过还是希望追书神器的API不要那么快就加密，否则只能解析百度了。不过追书好像不是很及时啊，在看的一本已经更新了，但是软件刷不出来（超品相师），而且追书神器也已经更新了。

**Comment by smuyyh** [comment]
我缓存了目录  所以可能是这个原因。后期再优化一下~
