### ISSUE TITLE
Translate README.md into English

### ISSUE THREAD

**Issue by Korb** [JustWayward/BookReader#256]
This will make it possible for not only developers who speak hieroglyphic language to participate in testing and developing the "BookReader" application.

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Korb** [comment]
> to fix your trouble check this solution click

![2024-10-25_09-07-14](https://github.com/user-attachments/assets/43e9462d-8439-495e-afe9-a94febb991df)

I find this questionable enough not to do it.

Also, this will hardly translate README.md into English.
