### ISSUE TITLE
阅读界面翻页

### ISSUE THREAD

**Issue by zengcanxiang** [JustWayward/BookReader#27]
使用中发现，在阅读界面左边，只能上一页，我的手势是右边往左边翻，相同的，右边就只能下一页。
我发现，我的手指一按到屏幕，其实我要干嘛程序就已经判断完了.......
这个是不是旧版的阅读界面的问题呢？
我的代码现在是9月30号的。之后的还没更新，但是我看记录没有关于阅读界面的更新，应该是影响的吧。

**Comment by smuyyh** [comment]
暂时是触摸就绘制下一页或上一页...  放开之后就翻页，不能取消，待优化
