### ISSUE TITLE
阅读时候点击中间出来工具栏的时候,  状态栏不显示

### ISSUE THREAD

**Issue by mdlboe** [JustWayward/BookReader#32]
状态栏不显示 不方便  看书的时候如果手机收到信息等, 如果点击中间能显示状态栏 就能看到,很方便 
现在这样不显示太不方便了

**Comment by smuyyh** [comment]
恩 因为像追书那样子状态栏显示的时候有一个动画  觉得不好看 就去掉了

**Comment by smuyyh** [comment]
@mdlboe 已解决，阅读页状态栏会跟随菜单栏显示与隐藏！
