### ISSUE TITLE
第一次打开程序时,进入书籍主界面时强制关闭

### ISSUE THREAD

**Issue by a442509097** [JustWayward/BookReader#37]
我的是SONY Z3v 5.1.1的系统, 另外问一下楼主, 我想实现一个简单的txt文本阅读, 楼主能否告诉我长文本时如何分批读取, 然后又能自动读取上次的观看位置, 只需告诉我一个思路就行, 或者你能告诉我你这个源码中那部分是关于这个的?

**Comment by smuyyh** [comment]
分页算法在PageFactory
