### ISSUE TITLE
打开首页，或者尾页，翻起来有可以动不了啦。

### ISSUE THREAD

**Issue by mppy1** [JustWayward/BookReader#39]
![image](https://cloud.githubusercontent.com/assets/5117395/19387092/97ef3b6e-924a-11e6-9d7d-2195b342764e.png)

**Comment by smuyyh** [comment]
对的。正在考虑解决优化~

**Comment by smuyyh** [comment]
@mppy1 已解决。

**Comment by mppy1** [comment]
这个问题没有解决好。没有上一页，或者最后一页了，很卡，动不了啦。

**Comment by mppy1** [comment]
网络图书从目录选择章节打开的时候自动会翻起一个书角，用的Le x630

**Comment by smuyyh** [comment]
有点坑…我正在改

**Comment by smuyyh** [comment]
改了，有空再帮忙试试还有没有这个问题哈  章节跳转 我这边试了几次都没有~

**Comment by mppy1** [comment]
![image](https://cloud.githubusercontent.com/assets/5117395/19507145/7dba3fac-9603-11e6-93f1-f8146d4587f5.png)

**Comment by mppy1** [comment]
还是没有好，这个有点坑了

**Comment by smuyyh** [comment]
坑爹   我这边不会啊...   你那是不是每次都会这样

**Comment by mppy1** [comment]
这个应该是事件穿透了，我点下面的Aa设置，像是点到页面上去翻页了，但翻到一半又不动了。

**Comment by smuyyh** [comment]
应该没有穿透   我这部分设置了可点击了  之前确实会穿透

**Comment by mppy1** [comment]
如果点击中间的时候，手稍微移动点，会触发翻页，menu两个事件

**Comment by smuyyh** [comment]
正中间么？不会啊...  点击中间位置的之后直接return false了，事件不会继续传递了吧

```
if (actiondownX >= mScreenWidth / 3 && actiondownX <= mScreenWidth * 2 / 3
                        && actiondownY >= mScreenHeight / 3 && actiondownY <= mScreenHeight * 2 / 3) {
                    listener.onCenterClick();
                    return false;
                }
```

**Comment by mppy1** [comment]
嗯，是点中间的，手稍微移动点，会触发翻页，menu两个事件
我用不同的手机都测试了一下，都会出现。

**Comment by brook19** [comment]
翻页这个问题是会偶像，不过比上一个版本频次低多了。应该是哪儿还有点儿问题。

**Comment by brook19** [comment]
翻页这个问题是会偶像，不过比上一个版本频次低多了。应该是哪儿还有点儿问题。

**Comment by brook19** [comment]
https://github.com/JustWayward/BookReader/issues/39

**Comment by hengtongjie** [comment]
我这边也遇到点击中间 页面过一会会自动翻页到中间就停住了

**Comment by smuyyh** [comment]
今天再优化了一下。试了一会  没有复现这个卡住的问题了
