### ISSUE TITLE
翻页效果

### ISSUE THREAD

**Issue by TonyJason** [JustWayward/BookReader#4]
项目很不错，请问翻页的效果能做到追书神器那样吗，感觉很舒服，我一直使用追书神器，体验很不错

**Comment by smuyyh** [comment]
新版的阅读界面正在进行中。准备做成追书那效果~   现在这个翻页后面会被替代掉。

**Comment by TonyJason** [comment]
可以加一下QQ:550764580吗，想讨论一些问题，那个阅读界面的文字还是不能适配，底部还有很多留白的地方，而且涉及到字体加大减小等等问题。

**Comment by smuyyh** [comment]
字体变换，这个目前还正在构思中~   挺麻烦的一件事，分页处理适配需要考虑到标点符号，占位大小跟汉字是不一样的，所以暂时会有一点偏差。

**Comment by TonyJason** [comment]
我用追书神器看小说的时候发现有很多都是收费的，但是用你的看，为什么目录那里不显示收费呢？

**Comment by smuyyh** [comment]
他收费貌似只是一个字段标记而已。至少我目前看见的都是这样，也就是说只要忽略这个，收费的文章应该还是可以照常看的。反正肯定不会做收费这个功能了~ 尽量保证收费的文章也能看。

**Comment by TonyJason** [comment]
具体是哪个字段啊，可以加你QQ交流一下吗，谢谢

**Comment by smuyyh** [comment]
352091626.   com.justwayward.reader.bean.BookToc   isVip字段

**Comment by hymanme** [comment]
@smuyyh 这相当于破解了收费的章节，这种做法感觉有点不太合适，毕竟使用了别人的api，还破解了收费项，能不能考虑一下这一点。如果这样继续下去，我想api会不会被加鉴权。那样就不太好了！

**Comment by nanweiqing** [comment]
读书时候的日夜间模式没效果，这是个bug吗
