### ISSUE TITLE
包名在android studio不支持大写

### ISSUE THREAD

**Issue by mppy1** [JustWayward/BookReader#40]
![image](https://cloud.githubusercontent.com/assets/5117395/19387232/73651e2a-924b-11e6-831b-bb6a7aa862d5.png)

**Comment by smuyyh** [comment]
支持啊。不过我已经改成小写了

**Comment by mppy1** [comment]
@smuyyh 嗯，是这样的，Android studio 是区分大小写的，但是git 大小写不敏感，所以就会出现自己的版本改了，但从git 上重新拉下来，改成小写的git上并没改，重新拉下来包名还是大写的。

**Comment by smuyyh** [comment]
是啊。所以改的时候我还的先删掉大写的 提交，然后再加入改成小写，再提交…略坑
