### ISSUE TITLE
内容更新不及时

### ISSUE THREAD

**Issue by jxxfzgy** [JustWayward/BookReader#41]
我发现有的书，比追书神器的内容更新慢，这是为什么，是接口权限的问题，还是业务逻辑处理导致的？

**Comment by smuyyh** [comment]
你这是什么时候的代码呢？最近这几天刚处理，不过还没测，主要就是目录缓存的问题

**Comment by jxxfzgy** [comment]
昨天晚上更新的代码

**Comment by jxxfzgy** [comment]
你看下太古星辰诀，对比下追书神器的

**Comment by jxxfzgy** [comment]
对了，我清了缓存还是一样的，我觉得这根缓存没有关系，而且不是说最近更新的没有同步，而是，相差几百章

**Comment by lfh1991** [comment]
@jxxfzgy VIP章节是抓不到的，《太古星辰诀》这本书只有VIP源能看到最新章节。
