### ISSUE TITLE
用之前的代码安装的app，直接运行最新代码，异常情况比较多

### ISSUE THREAD

**Issue by zengcanxiang** [JustWayward/BookReader#44]
可能是之前的数据与现在的逻辑不符合，动不动就因为一些时间字段报错，例如 更新时间排序,格式化追书神器返回的时间字符串，现在只能赶紧把书单抢救出来，重新弄了~~~

**Comment by smuyyh** [comment]
可能有做一些改动吧  所以缓存可能会冲突

**Comment by mppy1** [comment]
上周装的，这周更新装，运行也崩了。
