### ISSUE TITLE
进度问题

### ISSUE THREAD

**Issue by brook19** [JustWayward/BookReader#47]
导入本地书时。进度始终显示100%。单本书进度应该是全书长度的百分比。

**Comment by smuyyh** [comment]
恩。暂时没有比较好的办法去快速计算页数  所以还没改过来

**Comment by brook19** [comment]
可以考虑，记录每页读取内容大小，做累加处理，除以文件总大小，然后得出百分比。

**Comment by smuyyh** [comment]
这个是可以。感觉显示页数和总页数比较好   所以~
