### ISSUE TITLE
APP闪退

### ISSUE THREAD

**Issue by zhuduotao** [JustWayward/BookReader#49]
首次进入APP选择性别后，加载推荐列表，低概率闪退。TAB发现-分类-女性-（游戏竞技和莉莉两个子分类），大概率闪退。
表层原因是这两个页面的数据只有很少的几个，不能够填充满一页。
实质是EasyRecyclerView的OnRefresh在数据加载到绘制完成的过程中一直被调用。这个问题在页面数据铺满的时候不会造成大的问题。但是在数据不足一页的时候，EasyRecyclerView还会自动触发OnLoadMore方法。OnLoadMore方法会试图重绘制RecyclerView。但是刚刚上面说了，OnRefresh被调用了多次，有很大几率，在OnloadMore的时候，OnRefresh正在调用RecyclerArrayAdapter的clear方法，其中的notifyItemRangeRemoved(headers.size(), count)，会报错java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true。
目前的解决办法是在adapter的clear方法notifyItemRangeRemoved前先notifyDataSetChanged。可以避免闪退，但是并不能解决问题，他会不断加载重复的数据……
至于更好的解决方法……耦合太厉害，暂时下不了手。

**Comment by anshe80** [comment]
今天的更新下载编译安装后，每次进去书架就一直有个圈在那里加载，怎么点都不听，只能搜索一本书点击追书，阅读后再返回才可以看到书架的书。

**Comment by smuyyh** [comment]
嗯，这个正在解决

**Comment by lfh1991** [comment]
@anshe80 这个问题解决了。代码更新下吧
