### ISSUE TITLE
华为mat7 6.0 阅读页面有空白，弱弱的问下，没有我的书架吗

### ISSUE THREAD

**Issue by bingzi494** [JustWayward/BookReader#51]

**Comment by smuyyh** [comment]
书架在首页。阅读页面有空白是啥情况，能截个图么？

**Comment by bingzi494** [comment]
![image](https://cloud.githubusercontent.com/assets/13672830/19593177/d7fe9904-97b1-11e6-90b9-ac7ee8fe6059.png)

**Comment by smuyyh** [comment]
你这都已经很久之前的版本了…

**Comment by bingzi494** [comment]
～_～！
