### ISSUE TITLE
没找到类

### ISSUE THREAD

**Issue by AssassinLife** [JustWayward/BookReader#53]
import com.justwayward.reader.component.DaggerMainComponent;
并没有这个类

**Comment by smuyyh** [comment]
Build一下就好

**Comment by Pinick** [comment]
Dagger android studio兼容性不怎么好,每次都有Build下才会生成DaggerComponent

**Comment by smuyyh** [comment]
这也不算是兼容性问题吧  class阶段注解，通过编译生成

**Comment by Pinick** [comment]
只是不会自动生成,每次都有build有点麻烦,  android studio 大点的项目build的一下就要5分钟......

**Comment by smuyyh** [comment]
直接run也是可以的吧…五分钟…该换电脑了😂😂

**Comment by chenCoding** [comment]
这个是什么原理啊 这个类不是编写的吗
