### ISSUE TITLE
FileUtils 中空指针

### ISSUE THREAD

**Issue by TonyJason** [JustWayward/BookReader#56]
这个类里面的createRootPath方法里面 context.getExternalCacheDir().getPath()代码段在大部分上的4.4.4系统上返回空，，魅族 魅蓝Note(M1 note)特别是魅族和小米。

**Comment by smuyyh** [comment]
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
有加这个权限么...

**Comment by TonyJason** [comment]
加了，有的机型不会报错。魅族和小米会报错

**Comment by smuyyh** [comment]
这就怪了。 我云真机用小米note测  也不会出现这个错误啊~
