### ISSUE TITLE
开始阅读就崩溃啦

### ISSUE THREAD

**Issue by keien411** [JustWayward/BookReader#59]
点击开始阅读就报一个Toast              哎呀， 程序发生崩溃啦...
在书架里点击书也报这个Toast

java.lang.UnsatisfiedLinkError: Couldn't load hci_curl from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.justwayward.reader-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.justwayward.reader-2, /vendor/lib, /system/lib]]]: findLibrary returned null

**Comment by keien411** [comment]
可能是虚拟机的问题，我用真机安装了下就没有这个问题，可以点击进去阅读

**Comment by keien411** [comment]
阅读的 时候 左右划容易误触，唤出菜单

**Comment by smuyyh** [comment]
语音那套so库 虚拟机的CPU架构可能不支持。 不过现在也语音这块暂时隐藏了  后面再考虑要不要剔除掉

因为中间是action_down就弹出菜单，得优化一下改成单击

**Comment by smuyyh** [comment]
@keien411 改了。单击抬起的时候才唤出菜单！
