### ISSUE TITLE
缓存策略有问题

### ISSUE THREAD

**Issue by fhammer** [JustWayward/BookReader#60]
您是否注意过相关流的缓存数据问题，每次网络请求缓存和网络数据都会显示的，内容重复

**Comment by smuyyh** [comment]
每次网络请求缓存和网络数据都会显示的，内容重复？？

现在是先网络请求，保存到文件，再读取出来。

**Comment by fhammer** [comment]
流的数据确实会重复，我也反复验证了几次，大神是先网络请求缓存到文件，然后再读出来，可是在后面紧接着又做了数据合并Observable.concat操作，很可能是这里导致的，我是将每页数据改为6条这样重复会明显一些

**Comment by smuyyh** [comment]
哦你是说这个。这个没有细处理  本来是想为了节省等待时间   就先加载缓存  然后又做了网络请求。
