### ISSUE TITLE
哈哈! 用户体验不好啊

### ISSUE THREAD

**Issue by booldplx** [JustWayward/BookReader#61]
翻书时必须滑动距离很大才能翻页,不然就和点击是一个效果咯.---另外每次保持到书架的小说睡一觉起来就没有了...................必须重新去添加

**Comment by smuyyh** [comment]
书架会没了？没清缓存不会没把

**Comment by booldplx** [comment]
真心不骗你

**Comment by smuyyh** [comment]
问了好几个人  也没发现有这个问题。书架是保存在缓存中的~   或者更新一下代码试试。有确定情况再试试  哈哈

**Comment by tomoya92** [comment]
@smuyyh 我用着体验也不是太好，如果只用点击屏幕的方式看书倒没什么感觉，我是习惯了滑动屏幕看书，如果用左手在屏幕左边1/2区域往左滑是怎么也滑不过来的，必须要超过屏幕左边1/2处往左滑才行，这个体验真的就不太好了，希望作者能改进一下

**Comment by smuyyh** [comment]
@tomoya92 恩。目前确实是这样~   正在考虑改进
