### ISSUE TITLE
更新之后，怎么总是报网络异常

### ISSUE THREAD

**Issue by zengcanxiang** [JustWayward/BookReader#68]
之前还可以用，更新之后，就报
```java
 java.net.UnknownHostException: Unable to resolve host "api.zhuishushenqi.com": No address associated with hostname
```
但是浏览器都能打开，我还卸载重装了.是回调在onError错误中的.

**Comment by zengcanxiang** [comment]
而且，提一个建议,就是需要更新书架这方面的代码的时候，就是不会导致之前书架的书丢失. 
之前好几次更新，本地有书，然后一更新安装，书架没了..... 有一种淡淡的忧伤

**Comment by zengcanxiang** [comment]
之前可能是网络问题。不过，现在重新添加书架中~

**Comment by smuyyh** [comment]
现在没怎么更新书架这些代码了。其他细节也不大好优化了哎    UnknownHostException不应该呀，挺多天没改过代码了...   是不是手机网络问题

**Comment by zengcanxiang** [comment]
加油~ 等看明白了代码贡献一份力量~
