### ISSUE TITLE
切换夜间模式看不清三个Fragment的标题

### ISSUE THREAD

**Issue by finch0219** [JustWayward/BookReader#69]
切换夜间模式看不清三个Fragment的标题，再切回日间模式也看不清。完全退出再打开就能显示

**Comment by smuyyh** [comment]
三个Fragment？

**Comment by finch0219** [comment]
RVPIndicator mIndicator 的标题（书架，社区，发现）看不清

**Comment by smuyyh** [comment]
不会啊   我这儿很清楚啊。 你那啥时候的代码？
<img src="https://cloud.githubusercontent.com/assets/15133565/20477503/dbaf1110-b010-11e6-9e3a-749a1304945c.png" width=280 />
