### ISSUE TITLE
6.0以上默认关闭所有权限,导致获取数据时报这个异常java.lang.SecurityException: getDeviceId: Neither user 10158 nor current process has android.permission.READ_PHONE_STAT

### ISSUE THREAD

**Issue by gaoxuefeng** [JustWayward/BookReader#7]
6.0以上默认关闭所有权限,导致获取数据时报这个异常java.lang.SecurityException: getDeviceId: Neither user 10158 nor current process has android.permission.READ_PHONE_STAT
请在启动时判断 手机版本 并且6.0以上动态获取权限

**Comment by smuyyh** [comment]
对的。6.0权限适配还没处理~  thx
