### ISSUE TITLE
Android7.1.1 系统 通知栏也会有这个黑条

### ISSUE THREAD

**Issue by tomoya92** [JustWayward/BookReader#70]
qq也会有，百度人家都说这是利用了android之前通知栏的一个bug导致的，难道bookreader里也用了？
![image](https://cloud.githubusercontent.com/assets/6915570/20508621/cea1fbee-b09d-11e6-90ab-c036bbf86153.png)

**Comment by smuyyh** [comment]
没装7.1.1系统，还不知道有这些问题呀~~

**Comment by tomoya92** [comment]
你用模拟器试试看

**Comment by smuyyh** [comment]
今天刚装上7.1.1 才想起这个问题~ 

我这边是没出现黑栏这个bug。也没用到通知栏相关的东西，应该不是app本身的问题。
  
<img src="https://cloud.githubusercontent.com/assets/15133565/22635111/5fe701a4-ec6b-11e6-8996-72624d1b8ce5.png" width=300 />
