### ISSUE TITLE
能不能把阅读部分，单独分出来~！

### ISSUE THREAD

**Issue by Sabirjan** [JustWayward/BookReader#71]
您好！能不能把项目的阅读部分单独分出来，做一个阅读View项目，谢谢！
这个项目好像MVP模式，我正在做的是MVC,需要改的话，改很多地方。。。
你能不能帮我单独分出来，传递参数一个txt文件地址等...

**Comment by smuyyh** [comment]
这个就需要挺大工作量了...   自己 改也不难吧。

**Comment by Sabirjan** [comment]
我看这个https://github.com/bifan-wei/HwReader项目也不错，但是我还是选你的了~！
你最理解项目代码的，半天就可以了移植出来吧。。。
直接读本地的TXT文件，目录都不需要....阅读View体现出来就可以了

**Comment by smuyyh** [comment]
那就把readview包下几个文件拿出来就行了。 跟activity都没多大关系了。哪还有什么mvp...
