### ISSUE TITLE
在4.0，4.1 系统下运行翻页效果显示透明，请问这个要怎么处理

### ISSUE THREAD

**Issue by WeiJieJin** [JustWayward/BookReader#76]

**Comment by smuyyh** [comment]
放上截图看看~

**Comment by WeiJieJin** [comment]
![Uploading image.png…]()

**Comment by WeiJieJin** [comment]
![-1](https://cloud.githubusercontent.com/assets/5318927/20876884/00917b5e-bb00-11e6-9e78-aa5f44f13604.png)

**Comment by WeiJieJin** [comment]
![image](https://cloud.githubusercontent.com/assets/5318927/20876927/4625323c-bb00-11e6-8d53-a3b44d2e1835.png)

**Comment by WeiJieJin** [comment]
![image](https://cloud.githubusercontent.com/assets/5318927/20876946/698fca8e-bb00-11e6-9940-9ed0577f0510.png)

**Comment by smuyyh** [comment]
你是改过代码了还是？ 原来的代码不会这样吧？

**Comment by WeiJieJin** [comment]
在绘制文字的时候添加了一些判断，区分人名字

**Comment by smuyyh** [comment]
这个翻页效果总共要绘制四部分。 上页 下页  阴影  背面   所以你可能是绘制背面和阴影的时候 改错了吧。和源文件比对一下咯

**Comment by WeiJieJin** [comment]
谢谢 🙏
