### ISSUE TITLE
请教目录缓存

### ISSUE THREAD

**Issue by cocoas** [JustWayward/BookReader#80]
请问大神 ，BookReader的目录缓存是怎么做的啊，每次 进来的时候都请求目录然后缓存吗？

**Comment by smuyyh** [comment]
目前进入阅读界面是先加载缓存，再进行请求。具体参照```com.justwayward.reader.ui.presenter.BookReadPresenter```   目前这个也不是很完善，暂时是这么做的。

**Comment by cocoas** [comment]
大神 这个好像懂了 ，看了您的这个类。
我还有一个疑问 就是 ，我们每次读取一章的时候，是不是第一次就会把章节的所有内容都拿出来，而不是每一次翻页都会去内存里面读，然后显示出来啊 。

**Comment by cocoas** [comment]
是每次翻页的时候 都会计算分页吗

**Comment by smuyyh** [comment]
翻页的时候  根据position 去读取一页的内容，实时的  不是一次性读出来

**Comment by cocoas** [comment]
好勒 谢谢大神

**Comment by smuyyh** [comment]
客气客气~~
