### ISSUE TITLE
DaggerAppComponent这个类怎么移植？

### ISSUE THREAD

**Issue by Sabirjan** [JustWayward/BookReader#86]
DaggerAppComponent这个类怎么移植？
找不到...

    apt 'com.google.dagger:dagger-compiler:2.0.2'
    compile 'com.google.dagger:dagger:2.0.2'
    provided 'org.glassfish:javax.annotation:10.0-b28'
这些都加上了。。。

**Comment by smuyyh** [comment]
这是编译后自动生成的。
