### ISSUE TITLE
怎么从readview里长按取词啊？

### ISSUE THREAD

**Issue by oubindo** [JustWayward/BookReader#94]
大佬你好，我想借助你的项目思路去实现我的一个项目，但是我不知道怎么去从你的readview里去取出词来，类似于edittext那种长按截取句子的那种效果。请问你有一些什么思路吗

**Comment by smuyyh** [comment]
1. 文字是直接绘制在画布上的，要取出来可能有点难…  或许可以研究一下Textview源码是如何实现这个功能的。
2. 长按事件会和滑动翻页的触摸事件冲突，这个还不大好处理，暂时没有什么特别好的办法。

**Comment by oubindo** [comment]
你觉得这个思路怎么样：
1.自定义两个类似于selectHandler的view，通过这两个view的x和y去判断是第几个字，然后对readview不断重绘，画出那种选择的背景，这是第一种想法。
2.第二种想法就是使用Textview来做整个项目。这样截取之类的操作就方便很多了

**Comment by ZhangYuShui** [comment]
你在说什么啊？有事加个qq详谈吧。1285436001




发件人：张玉水
Tel    ：13811239031
zys1285436001@163.com
 
发件人： oubindo
发送时间： 2017-02-01 14:41
收件人： JustWayward/BookReader
抄送： Subscribed
主题： Re: [JustWayward/BookReader] 怎么从readview里长按取词啊？ (#94)
你觉得这个思路怎么样：
1.自定义两个类似于selectHandler的view，通过这两个view的x和y去判断是第几个字，然后对readview不断重绘，画出那种选择的背景，这是第一种想法。
2.第二种想法就是使用Textview来做整个项目。这样截取之类的操作就方便很多了

**Comment by smuyyh** [comment]
@oubindo 第一个方式或许可行，第二个用Textview对阅读器来说并不好，就很难排版与计算每页字数了。
