### ISSUE TITLE
请问能详细介绍下如何使用该项目中截取的API吗？

### ISSUE THREAD

**Issue by HuanYeXingYu** [JustWayward/BookReader#97]

**Comment by smuyyh** [comment]
如何截取可参考：[http://blog.csdn.net/yyh352091626/article/details/52759294](http://blog.csdn.net/yyh352091626/article/details/52759294)

本项目的API可在com.justwayward.bookreader.api下查看，有注释。具体接口不明白的再说~

**Comment by azaxas128** [comment]
@smuyyh 有兴趣来追书这边看看机会莫，诚邀~ 微信：w328768132 qq:328768132
