### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by HuanYeXingYu** [JustWayward/BookReader#99]
您好，我正在自学抓包获取API，您的项目做得很好，但我自身水品过低，请问可以把你这个项目中抓包获取Json数据的部分独立出来做个Demo吗？像把请求  发现->分类 获取的数据赋予到TextView中。若是可以不胜感激。我QQ：1031158253

**Comment by smuyyh** [comment]
这个你可以直接看api接口和调用。
